# Generated by Django 5.2.17 on 2026-10-02 11:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtensionConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("extension", models.CharField(db_index=True, max_length=64)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "use_instance",
                    models.BooleanField(
                        default=False,
                        help_text="Event rows only: use the instance-wide connection instead of an own one.",
                    ),
                ),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("secrets_encrypted", models.TextField(blank=True)),
                ("features", models.JSONField(blank=True, default=dict)),
                ("webhook_secret_encrypted", models.TextField(blank=True)),
                (
                    "health",
                    models.CharField(
                        choices=[
                            ("unknown", "Not tested"),
                            ("ok", "OK"),
                            ("error", "Error"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("last_check_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_configs",
                        to="events.event",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtensionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warn", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=8,
                    ),
                ),
                ("message", models.CharField(max_length=500)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="extensions.extensionconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InboundDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_id", models.CharField(max_length=200)),
                ("event_type", models.CharField(blank=True, max_length=100)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.PositiveSmallIntegerField(default=200)),
                ("response", models.JSONField(blank=True, default=dict)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound_deliveries",
                        to="extensions.extensionconfig",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="extensionconfig",
            constraint=models.UniqueConstraint(
                fields=("extension", "event"), name="uniq_extension_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="extensionconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event__isnull", True)),
                fields=("extension",),
                name="uniq_extension_instance",
            ),
        ),
        migrations.AddConstraint(
            model_name="inbounddelivery",
            constraint=models.UniqueConstraint(
                fields=("config", "delivery_id"), name="uniq_inbound_delivery"
            ),
        ),
    ]
