# Generated by Django 5.2.17 on 2026-10-10 20:32

import apps.ops.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("venues", "0004_floor_georeference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EscalationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                (
                    "min_severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="high",
                        max_length=10,
                        verbose_name="from severity",
                    ),
                ),
                (
                    "categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Empty: all categories.",
                        verbose_name="categories",
                    ),
                ),
                (
                    "after_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0: as soon as the incident is reported.",
                        verbose_name="after (minutes)",
                    ),
                ),
                (
                    "until",
                    models.CharField(
                        choices=[
                            ("unacknowledged", "not acknowledged"),
                            ("unresolved", "not resolved"),
                        ],
                        default="unacknowledged",
                        max_length=14,
                        verbose_name="while the incident is",
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Notification channels (ntfy, Matrix, e-mail, …) of this event.",
                        verbose_name="channels",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalation_rules",
                        to="events.event",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="events.role",
                        verbose_name="notify roles",
                    ),
                ),
            ],
            options={
                "ordering": ["after_minutes", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="number")),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "category",
                    models.CharField(
                        default="other", max_length=40, verbose_name="category"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="severity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("acknowledged", "Acknowledged"),
                            ("in_progress", "In progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="where exactly"
                    ),
                ),
                (
                    "team",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Security, Medics",
                        max_length=80,
                        verbose_name="team",
                    ),
                ),
                (
                    "reported_by",
                    models.CharField(
                        blank=True,
                        help_text="Who reported it (a name, a radio call sign, a phone number).",
                        max_length=120,
                        verbose_name="reported by",
                    ),
                ),
                ("links", models.JSONField(blank=True, default=list)),
                (
                    "source",
                    models.CharField(
                        blank=True, help_text="manual, api, dial, …", max_length=60
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned to",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="events.event",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="venues.room",
                        verbose_name="room",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="venues.zone",
                        verbose_name="zone",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Escalation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rule_name", models.CharField(max_length=120)),
                ("at", models.DateTimeField(auto_now_add=True)),
                ("recipients", models.PositiveIntegerField(default=0)),
                ("channels", models.JSONField(default=list)),
                (
                    "rule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ops.escalationrule",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="ops.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["at"],
            },
        ),
        migrations.CreateModel(
            name="IncidentUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("note", "Note"),
                            ("status", "Status"),
                            ("assigned", "Assigned"),
                            ("severity", "Severity"),
                            ("edited", "Edited"),
                            ("escalated", "Escalated"),
                            ("link", "Linked"),
                            ("attachment", "Attachment"),
                        ],
                        max_length=12,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        max_length=300,
                        upload_to=apps.ops.models.attachment_path,
                    ),
                ),
                ("attachment_name", models.CharField(blank=True, max_length=200)),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="ops.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["at"],
            },
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("at", models.DateTimeField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("message", "Message"), ("system", "System")],
                        default="message",
                        max_length=8,
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Security 2",
                        max_length=80,
                        verbose_name="from",
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Control",
                        max_length=80,
                        verbose_name="to",
                    ),
                ),
                ("text", models.TextField(verbose_name="message")),
                (
                    "important",
                    models.BooleanField(default=False, verbose_name="important"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="system entries: the event type",
                        max_length=80,
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        blank=True,
                        help_text="idempotency key of offline entries",
                        max_length=64,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ops_log",
                        to="events.event",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="log",
                        to="ops.incident",
                        verbose_name="incident",
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="task")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "team",
                    models.CharField(blank=True, max_length=80, verbose_name="team"),
                ),
                (
                    "due_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="due"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("done", "Done")],
                        default="open",
                        max_length=6,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned to",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ops_tasks",
                        to="events.event",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="ops.incident",
                        verbose_name="incident",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "due_at", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["event", "status"], name="ops_inciden_event_i_5b99dc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="incident",
            constraint=models.UniqueConstraint(
                fields=("event", "number"), name="ops_incident_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="escalation",
            constraint=models.UniqueConstraint(
                fields=("incident", "rule"), name="ops_escalation_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="logentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_id", ""), _negated=True),
                fields=("event", "client_id"),
                name="ops_log_client_id",
            ),
        ),
    ]
