# Generated by Django 5.2.17 on 2026-10-02 11:52

import apps.events.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used in URLs: /e/<short name>/",
                        unique=True,
                        validators=[apps.events.models.validate_slug],
                        verbose_name="short name",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("setup", "Setup"),
                            ("live", "Live"),
                            ("teardown", "Teardown"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        max_length=64,
                        validators=[apps.events.models.validate_timezone],
                        verbose_name="time zone",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="first day"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="last day"),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="events/logos/"),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#2563eb",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$", "Use a hex colour like #1d4ed8."
                            )
                        ],
                        verbose_name="primary colour",
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#22d3ee",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$", "Use a hex colour like #1d4ed8."
                            )
                        ],
                        verbose_name="accent colour",
                    ),
                ),
                (
                    "default_theme",
                    models.CharField(
                        blank=True,
                        help_text="Theme key used by screens (Phase 1 designer).",
                        max_length=64,
                        verbose_name="default theme",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venues",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="venues.venue"
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__email"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField()),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("permissions", models.JSONField(blank=True, default=list)),
                (
                    "require_2fa",
                    models.BooleanField(
                        default=False, verbose_name="require two-factor authentication"
                    ),
                ),
                ("builtin", models.BooleanField(default=False, editable=False)),
                ("order", models.PositiveSmallIntegerField(default=100)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("scope_kind", models.CharField(blank=True, max_length=32)),
                ("scope_id", models.CharField(blank=True, max_length=64)),
                ("scope_label", models.CharField(blank=True, max_length=200)),
                (
                    "token_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="events.event",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="events.role",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope_kind", models.CharField(blank=True, max_length=32)),
                ("scope_id", models.CharField(blank=True, max_length=64)),
                ("scope_label", models.CharField(blank=True, max_length=200)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="events.membership",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="events.role",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("setup", "Setup"),
                            ("live", "Live"),
                            ("teardown", "Teardown"),
                            ("archived", "Archived"),
                        ],
                        max_length=10,
                    ),
                ),
                ("at", models.DateTimeField(db_index=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=300)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_transitions",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["at"],
            },
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="uniq_membership"
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("event", "key"), name="uniq_role_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.UniqueConstraint(
                fields=("membership", "role", "scope_kind", "scope_id"),
                name="uniq_role_assignment",
            ),
        ),
    ]
