# Generated by Django 5.2.17 on 2026-10-10 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("announcements", "0005_speech_recorded"),
        ("events", "0001_initial"),
        ("extensions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DectAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=40)),
                ("severity", models.CharField(blank=True, max_length=10)),
                ("message", models.CharField(blank=True, max_length=500)),
                ("rfp", models.CharField(blank=True, max_length=120)),
                ("dial_id", models.CharField(blank=True, max_length=40)),
                ("at", models.DateTimeField(db_index=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dial_dect_alerts",
                        to="extensions.extensionconfig",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dial_dect_alerts",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "extension",
                    models.CharField(max_length=40, verbose_name="DIAL extension"),
                ),
                ("audio", models.CharField(blank=True, max_length=300)),
                ("dial_announcement", models.CharField(blank=True, max_length=40)),
                ("duration", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("imported", "Imported"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=10,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=300)),
                ("transcript", models.TextField(blank=True)),
                ("speech_file", models.CharField(blank=True, max_length=80)),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="announcements.announcement",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dial_recordings",
                        to="extensions.extensionconfig",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dial_recordings",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("emergency", "Ring handsets (emergency broadcast)"),
                            ("message", "DECT text message"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("evacuation", "Evacuation"),
                            ("announcement", "Announcement"),
                            ("test", "Test"),
                        ],
                        max_length=12,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("text", models.TextField()),
                ("group", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("targets", models.PositiveIntegerField(default=0)),
                ("detail", models.CharField(blank=True, max_length=500)),
                ("response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dial_broadcasts",
                        to="extensions.extensionconfig",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dial_broadcasts",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("reference", ""), _negated=True),
                        fields=("config", "kind", "source", "reference"),
                        name="dial_broadcast_once",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoleMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dial_role",
                    models.CharField(max_length=40, verbose_name="DIAL role"),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dial_roles",
                        to="extensions.extensionconfig",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="events.role",
                        verbose_name="EVAC role",
                    ),
                ),
            ],
            options={
                "ordering": ["dial_role"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("config", "dial_role"), name="dial_role_once"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=20)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dial_snapshots",
                        to="extensions.extensionconfig",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("config", "key"), name="dial_snapshot_once"
                    )
                ],
            },
        ),
    ]
