# Generated by Django 5.2.17 on 2026-10-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dial", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="source",
            field=models.CharField(
                choices=[
                    ("evacuation", "Evacuation"),
                    ("announcement", "Announcement"),
                    ("alert", "Staff alert"),
                    ("test", "Test"),
                ],
                max_length=12,
            ),
        ),
    ]
