# Generated by Django 5.2.17 on 2026-10-10 14:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeEvent",
            fields=[
                ("event_id", models.UUIDField(primary_key=True, serialize=False)),
                ("slug", models.SlugField(max_length=80)),
                ("checkout_id", models.UUIDField(blank=True, null=True)),
                ("checked_out", models.BooleanField(default=True)),
                ("checkin_requested", models.BooleanField(default=False)),
                ("snapshot_version", models.CharField(blank=True, max_length=64)),
                ("snapshot_at", models.DateTimeField(blank=True, null=True)),
                ("seeded", models.BooleanField(default=False)),
                ("next_seq", models.PositiveBigIntegerField(default=1)),
                ("pushed_seq", models.PositiveBigIntegerField(default=0)),
                ("action_after", models.PositiveBigIntegerField(default=0)),
                ("files_missing", models.PositiveIntegerField(default=0)),
                ("files", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="NodeIdentity",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("node_id", models.UUIDField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("central_url", models.URLField(blank=True)),
                ("ca_file", models.CharField(blank=True, max_length=300)),
                ("sign_private_encrypted", models.TextField(blank=True)),
                ("box_private_encrypted", models.TextField(blank=True)),
                ("sign_public", models.CharField(blank=True, max_length=64)),
                ("box_public", models.CharField(blank=True, max_length=64)),
                ("token_encrypted", models.TextField(blank=True)),
                ("enrolled_at", models.DateTimeField(blank=True, null=True)),
                ("last_contact", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code_hash", models.CharField(blank=True, max_length=64)),
                ("code_expires_at", models.DateTimeField(blank=True, null=True)),
                ("sign_public", models.CharField(blank=True, max_length=64)),
                ("box_public", models.CharField(blank=True, max_length=64)),
                (
                    "token_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("enrolled_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("last_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("version", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "checked out"),
                            ("checkin_requested", "check-in requested"),
                            ("checked_in", "checked in"),
                            ("forced", "forced check-in"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("applied_seq", models.PositiveBigIntegerField(default=0)),
                ("seeded", models.BooleanField(default=False)),
                ("snapshot_version", models.CharField(blank=True, max_length=64)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "ended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_checkouts",
                        to="events.event",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkouts",
                        to="nodes.node",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="OpLogEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_id", models.UUIDField(db_index=True)),
                ("node_id", models.UUIDField(blank=True, null=True)),
                ("seq", models.PositiveBigIntegerField()),
                ("key", models.CharField(max_length=100)),
                ("kind", models.CharField(max_length=10)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField()),
                ("pushed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["event_id", "seq"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key",), name="nodes_oplog_unique_key"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProxiedAction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("kind", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("actor_repr", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "waiting for the node"),
                            ("done", "done"),
                            ("failed", "failed"),
                            ("expired", "expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "checkout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="nodes.checkout",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ReceivedOp",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("seq", models.PositiveBigIntegerField()),
                ("key", models.CharField(max_length=100, unique=True)),
                ("kind", models.CharField(max_length=10)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField()),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checkout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ops",
                        to="nodes.checkout",
                    ),
                ),
            ],
            options={
                "ordering": ["checkout", "seq"],
            },
        ),
        migrations.AddConstraint(
            model_name="checkout",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["active", "checkin_requested"])),
                fields=("event",),
                name="nodes_one_open_checkout_per_event",
            ),
        ),
    ]
