# Generated by Django 5.2.17 on 2026-10-09 23:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("json", "JSON (HTTP)"),
                            ("rss", "RSS or Atom feed"),
                            ("ical", "iCal calendar"),
                            ("csv", "CSV (e.g. a spreadsheet export)"),
                            ("source", "EVAC data source"),
                        ],
                        default="json",
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, max_length=1000, verbose_name="URL"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="data source"
                    ),
                ),
                ("auth_header_encrypted", models.TextField(blank=True)),
                (
                    "poll_seconds",
                    models.PositiveIntegerField(
                        default=300, verbose_name="refresh every (seconds)"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not fetched yet"),
                            ("ok", "OK"),
                            ("error", "Error"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=500)),
                ("last_fetch_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("snapshot", models.JSONField(blank=True, null=True)),
                ("snapshot_hash", models.CharField(blank=True, max_length=64)),
                ("etag", models.CharField(blank=True, max_length=200)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_feeds",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CustomWidget",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "items_path",
                    models.CharField(
                        default="$",
                        help_text="JSONPath of the list of items, e.g. $.items or $.data[*]. $: the whole result.",
                        max_length=300,
                        verbose_name="items",
                    ),
                ),
                ("fields", models.JSONField(blank=True, default=dict)),
                (
                    "visual",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("list", "List"),
                            ("table", "Table"),
                            ("cards", "Cards"),
                            ("counter", "Counter"),
                            ("gauge", "Gauge"),
                            ("ticker", "Ticker"),
                            ("bars", "Bar chart"),
                        ],
                        default="list",
                        max_length=10,
                        verbose_name="visual",
                    ),
                ),
                ("options", models.JSONField(blank=True, default=dict)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_widgets",
                        to="events.event",
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="widgets",
                        to="widgets.feed",
                        verbose_name="feed",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
