# Generated by Django 5.2.17 on 2026-10-02 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetoken",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="Restrict the token to one event; empty = all events of the owner.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_tokens",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="servicetoken",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="totpdevice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="totp_devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="webauthncredential",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webauthn_credentials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
