# Generated by Django 5.2.17 on 2026-10-10 21:21

import apps.crew.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("venues", "0004_floor_georeference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew_shift_types",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. First aid, Forklift",
                        max_length=80,
                        verbose_name="name",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew_skills",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "colour",
                    models.CharField(
                        default="#2563eb", max_length=7, verbose_name="colour"
                    ),
                ),
                (
                    "meeting_point",
                    models.CharField(
                        blank=True,
                        help_text="Where the team meets, used in crew calls.",
                        max_length=120,
                        verbose_name="meeting point",
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=60)),
                ("external_id", models.CharField(blank=True, max_length=100)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew_teams",
                        to="events.event",
                    ),
                ),
                (
                    "leads",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="team leads",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="title")),
                (
                    "location",
                    models.CharField(blank=True, max_length=150, verbose_name="where"),
                ),
                ("starts_at", models.DateTimeField(verbose_name="starts")),
                ("ends_at", models.DateTimeField(verbose_name="ends")),
                (
                    "needed",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="people needed"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "open_signup",
                    models.BooleanField(
                        default=True,
                        help_text="Crew can sign up themselves in the staff app.",
                        verbose_name="open for sign-up",
                    ),
                ),
                (
                    "checkin_token",
                    models.CharField(
                        default=apps.crew.models._token,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=60)),
                ("external_id", models.CharField(blank=True, max_length=100)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew_shifts",
                        to="events.event",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="venues.room",
                        verbose_name="room",
                    ),
                ),
                (
                    "shift_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crew.shifttype",
                        verbose_name="type",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="crew.skill",
                        verbose_name="skills needed",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="crew.team",
                        verbose_name="team",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at", "team__name"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        help_text="Phone or DECT number.",
                        max_length=120,
                        verbose_name="contact",
                    ),
                ),
                ("arrived", models.BooleanField(default=False, verbose_name="arrived")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("source", models.CharField(blank=True, max_length=60)),
                ("external_id", models.CharField(blank=True, max_length=100)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew_members",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crew_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="account",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="members",
                        to="crew.skill",
                        verbose_name="skills",
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(
                        blank=True,
                        related_name="members",
                        to="crew.team",
                        verbose_name="teams",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("signed_up", "Signed up"),
                            ("checked_in", "Checked in"),
                            ("done", "Done"),
                            ("no_show", "No-show"),
                        ],
                        default="signed_up",
                        max_length=10,
                    ),
                ),
                ("signed_up_at", models.DateTimeField(auto_now_add=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("checked_out_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=60)),
                (
                    "by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="crew.member",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="crew.shift",
                    ),
                ),
            ],
            options={
                "ordering": ["shift__starts_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shift", "member"), name="crew_assignment_once"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="shifttype",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="crew_shifttype_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="crew_skill_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="crew_team_name"
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["event", "starts_at"], name="crew_shift_event_i_dbbd2e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("event", "user"),
                name="crew_member_user",
            ),
        ),
    ]
