# Generated by Django 5.2.17 on 2026-10-09 16:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0003_layouts"),
        ("events", "0001_initial"),
        ("screens", "0002_remote_management"),
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(max_length=40)),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Higher ranks win when several announcements show.",
                        verbose_name="rank",
                    ),
                ),
                (
                    "colour",
                    models.CharField(
                        default="#2563eb", max_length=7, verbose_name="colour"
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        choices=[
                            ("banner", "Banner along the bottom"),
                            ("ticker", "Scrolling ticker"),
                            ("card", "Card over the content"),
                            ("takeover", "Full screen"),
                        ],
                        default="banner",
                        max_length=10,
                        verbose_name="on screens",
                    ),
                ),
                (
                    "sound",
                    models.CharField(
                        choices=[
                            ("none", "No sound"),
                            ("chime", "Chime"),
                            ("gong", "Gong"),
                            ("alert", "Alert tone"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="sound",
                    ),
                ),
                (
                    "min_display_seconds",
                    models.PositiveIntegerField(
                        default=30, verbose_name="show for at least (seconds)"
                    ),
                ),
                (
                    "repeat_every_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0: show once. Otherwise again until it ends.",
                        verbose_name="repeat every (minutes)",
                    ),
                ),
                (
                    "default_channels",
                    models.JSONField(
                        blank=True, default=list, verbose_name="default channels"
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False, verbose_name="always needs approval"
                    ),
                ),
                (
                    "emergency",
                    models.BooleanField(
                        default=False,
                        help_text="Needs the emergency permission (two-factor session), skips approval and takes over screens above live overrides.",
                        verbose_name="emergency level",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_levels",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-rank", "name"],
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("body", models.TextField(blank=True, verbose_name="text")),
                (
                    "short",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="short text (SMS, ticker)",
                    ),
                ),
                ("builtin", models.BooleanField(default=False, editable=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_templates",
                        to="events.event",
                    ),
                ),
                (
                    "layout",
                    models.ForeignKey(
                        blank=True,
                        help_text="Its texts may use {{ announcement.title }} and {{ announcement.text }}.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="content.layout",
                        verbose_name="layout for full-screen display",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="announcements.level",
                        verbose_name="level",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("variables", models.JSONField(blank=True, default=dict)),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("body", models.TextField(blank=True, verbose_name="text")),
                (
                    "short",
                    models.CharField(
                        blank=True,
                        help_text="Empty: the title.",
                        max_length=160,
                        verbose_name="short text (SMS, ticker)",
                    ),
                ),
                (
                    "all_screens",
                    models.BooleanField(default=True, verbose_name="everywhere"),
                ),
                (
                    "channels",
                    models.JSONField(blank=True, default=list, verbose_name="channels"),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="send at"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Empty: the level's display time (or until cancelled when it repeats).",
                        null=True,
                        verbose_name="show until",
                    ),
                ),
                (
                    "recurrence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Once"),
                            ("daily", "Every day"),
                            ("weekly", "Every week"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="repeat",
                    ),
                ),
                (
                    "recurrence_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="repeat until"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Waiting for approval"),
                            ("scheduled", "Scheduled"),
                            ("live", "Published"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("ended", "Ended"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.CharField(blank=True, max_length=300)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("last_occurrence", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="events.event",
                    ),
                ),
                (
                    "rooms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="venues.room",
                        verbose_name="rooms",
                    ),
                ),
                (
                    "screen_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="screens.screengroup",
                        verbose_name="screen groups",
                    ),
                ),
                (
                    "screens",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="screens.screen",
                        verbose_name="screens",
                    ),
                ),
                (
                    "venues",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="venues.venue",
                        verbose_name="venues",
                    ),
                ),
                (
                    "zones",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="venues.zone",
                        verbose_name="zones",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements",
                        to="announcements.level",
                        verbose_name="level",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="announcements.template",
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("channel", models.CharField(max_length=40)),
                ("occurrence", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Delivered"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("recipients", models.PositiveIntegerField(default=0)),
                ("detail", models.CharField(blank=True, max_length=500)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="announcements.announcement",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("announcement", "channel", "occurrence"),
                        name="announcements_delivery_unique",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="level",
            constraint=models.UniqueConstraint(
                fields=("event", "key"), name="announcements_level_unique_key"
            ),
        ),
    ]
