# Generated by Django 5.2.17 on 2026-10-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="channel_texts",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
