# Generated by Django 5.2.17 on 2026-10-09 22:50

from django.db import migrations, models


def _speak_defaults(apps, schema_editor):
    apps.get_model("announcements", "Level").objects.filter(key__in=["urgent", "emergency"]).update(speak=True)


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0002_channel_texts"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="speech_detail",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="announcement",
            name="speech_file",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="announcement",
            name="speech_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not spoken"),
                    ("pending", "Being prepared"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                    ("unavailable", "No voice installed"),
                ],
                default="",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="level",
            name="speak",
            field=models.BooleanField(
                default=False,
                help_text="Screens with sound speak the announcement (offline speech, when a voice is installed).",
                verbose_name="read aloud on screens",
            ),
        ),
        migrations.RunPython(_speak_defaults, migrations.RunPython.noop),
    ]
