# Generated by Django 5.2.17 on 2026-10-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0003_speech"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="anchor",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="relative to"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="anchor_edge",
            field=models.CharField(
                choices=[("start", "start"), ("end", "end")],
                default="start",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="anchor_label",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="announcement",
            name="anchor_offset",
            field=models.IntegerField(
                default=0, help_text="minutes; negative = before"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="audiences",
            field=models.JSONField(blank=True, default=list, verbose_name="audiences"),
        ),
    ]
