# Generated by Django 5.2.17 on 2026-10-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0004_audiences_and_anchors"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="speech_recorded",
            field=models.BooleanField(default=False),
        ),
    ]
