# Generated by Django 5.2.17 on 2026-10-09 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetFolder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_folders",
                        to="events.event",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="content.assetfolder",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FontFamily",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sans", "Sans serif"),
                            ("serif", "Serif"),
                            ("mono", "Monospace"),
                            ("display", "Display"),
                        ],
                        default="sans",
                        max_length=10,
                    ),
                ),
                (
                    "fallback",
                    models.CharField(
                        blank=True,
                        help_text="CSS font stack used while the font loads or for missing glyphs.",
                        max_length=300,
                        verbose_name="fallback fonts",
                    ),
                ),
                (
                    "licence",
                    models.TextField(
                        blank=True,
                        help_text="Where the font comes from and under which licence it may be used.",
                        verbose_name="licence note",
                    ),
                ),
                ("builtin", models.BooleanField(default=False, editable=False)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="font_families",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "font families",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FontFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sha256", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "static_path",
                    models.CharField(
                        blank=True,
                        help_text="built-in fonts ship as static files",
                        max_length=200,
                    ),
                ),
                ("original_name", models.CharField(blank=True, max_length=200)),
                ("original_format", models.CharField(blank=True, max_length=8)),
                ("weight_min", models.PositiveSmallIntegerField(default=400)),
                ("weight_max", models.PositiveSmallIntegerField(default=400)),
                (
                    "style",
                    models.CharField(
                        choices=[("normal", "normal"), ("italic", "italic")],
                        default="normal",
                        max_length=8,
                    ),
                ),
                ("axes", models.JSONField(blank=True, default=list)),
                ("unicode_range", models.CharField(blank=True, max_length=500)),
                ("size", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="content.fontfamily",
                    ),
                ),
            ],
            options={
                "ordering": ["family__name", "style", "weight_min"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Describes the content for people who cannot see it.",
                        max_length=300,
                        verbose_name="alternative text",
                    ),
                ),
                (
                    "credit",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="credit / licence"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "image"),
                            ("svg", "SVG"),
                            ("video", "video"),
                            ("audio", "audio"),
                            ("pdf", "PDF"),
                            ("lottie", "Lottie animation"),
                        ],
                        max_length=8,
                    ),
                ),
                ("mime", models.CharField(max_length=100)),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("original_name", models.CharField(max_length=255)),
                ("extension", models.CharField(max_length=10)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("variants", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "processing"),
                            ("ready", "ready"),
                            ("failed", "failed"),
                        ],
                        default="processing",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="events.event",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="content.assetfolder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "sha256"),
                        name="content_asset_unique_per_owner",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("tokens", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="themes",
                        to="events.event",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tokens not set here are inherited from this theme.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="content.theme",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "key"), name="content_theme_unique_key"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("event__isnull", True)),
                        fields=("key",),
                        name="content_theme_unique_shared_key",
                    ),
                ],
            },
        ),
    ]
