// SPDX-License-Identifier: AGPL-3.0-or-later
// Imports the official ISO 7010 safety signs EVAC uses from @iso-safety-signs/core (MIT) into
// src/renderer/iso7010.generated.ts. The artwork is copied unchanged except for one mechanical step: inline
// ``style="..."`` declarations become the equivalent SVG presentation attributes, because the screens' Content
// Security Policy blocks inline styles. Anything else unexpected (scripts, event handlers, unknown style
// properties) stops the import. Run: npm run iso7010 (CI checks the committed file is current).
import { createRequire } from "node:module";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const require = createRequire(import.meta.url);
const pkg = JSON.parse(readFileSync(join(dirname(require.resolve("@iso-safety-signs/core")), "..", "..", "package.json"), "utf8"));
const { getAllSigns } = require("@iso-safety-signs/core");

export const CODES = ["E001", "E002", "E003", "E007", "W001"];
const PRESENTATION = new Set(["display", "fill", "fill-opacity", "fill-rule", "stroke", "stroke-width",
  "stroke-opacity", "stroke-linecap", "stroke-linejoin", "stroke-miterlimit", "opacity", "clip-rule"]);

export function cspSafe(svg, code) {
  if (/<script|<style|\son[a-z]+\s*=|javascript:|<foreignObject|xlink:href="(?!#)|href="(?!#)/i.test(svg)) {
    throw new Error(`${code}: unexpected active content`);
  }
  return svg.replace(/\sstyle="([^"]*)"/g, (_m, decl) => {
    const attrs = decl.split(";").map((d) => d.trim()).filter(Boolean).map((d) => {
      const [prop, ...rest] = d.split(":");
      const name = prop.trim();
      if (!PRESENTATION.has(name)) throw new Error(`${code}: style property ${name} has no attribute form`);
      return ` ${name}="${rest.join(":").trim()}"`;
    });
    return attrs.join("");
  }).replace(/^<svg([^>]*)>/, (_m, a) => `<svg${a.replace(/\s(width|height)="[^"]*"/g, "")}>`);
}

export function build() {
  const all = getAllSigns();
  const signs = {};
  for (const code of CODES) {
    const sign = all.find((s) => s.code === code);
    if (!sign) throw new Error(`${code} is missing from @iso-safety-signs/core ${pkg.version}`);
    signs[code] = { name: sign.name, svg: cspSafe(sign.svg, code) };
  }
  return `// Generated by scripts/import-iso7010.mjs from ${pkg.name} ${pkg.version} (${pkg.license} licence,
// ${pkg.repository.url.replace(/^git\+/, "")}). ISO 7010 signs as published there; only inline styles were turned
// into SVG attributes for the Content Security Policy. Do not edit: run npm run iso7010.
// Licence: src/renderer/iso7010.LICENSE (kept in the built bundles by the comment below).
/*! ISO 7010 safety signs from ${pkg.name} ${pkg.version}: Copyright (c) Karl Norling, MIT licence */
export const ISO7010_SOURCE = ${JSON.stringify(`${pkg.name}@${pkg.version}`)};
export const ISO7010: Record<string, { name: string; svg: string }> = ${JSON.stringify(signs, null, 1)};
`;
}

const out = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "renderer", "iso7010.generated.ts");
if (process.argv[1] && import.meta.url !== pathToFileURL(process.argv[1]).href) {
  // imported (tests): nothing to write
} else if (process.argv.includes("--check")) {
  const text = build();
  if (readFileSync(out, "utf8") !== text) {
    console.error("src/renderer/iso7010.generated.ts is out of date: run npm run iso7010");
    process.exit(1);
  }
} else {
  const text = build();
  writeFileSync(out, text);
  console.log(`wrote ${out} (${CODES.join(", ")} from ${pkg.name}@${pkg.version})`);
}
