# Generated by Django 5.2.17 on 2026-10-09 11:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Screen",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("position_x", models.FloatField(blank=True, null=True)),
                ("position_y", models.FloatField(blank=True, null=True)),
                (
                    "token_hash",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "token_prefix",
                    models.CharField(blank=True, editable=False, max_length=24),
                ),
                ("paired_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_seen_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("reported", models.JSONField(blank=True, default=dict)),
                (
                    "health_state",
                    models.CharField(
                        choices=[
                            ("unpaired", "not paired"),
                            ("online", "online"),
                            ("stale", "stale"),
                            ("offline", "offline"),
                            ("revoked", "revoked"),
                        ],
                        default="unpaired",
                        max_length=10,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screens",
                        to="events.event",
                    ),
                ),
                (
                    "paired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="venues.room",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="venues.venue",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="venues.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PairingRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=6)),
                ("secret_hash", models.CharField(editable=False, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("info", models.JSONField(blank=True, default=dict)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("token_encrypted", models.TextField(blank=True, editable=False)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "screen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="screens.screen",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScreenGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("manual", "Manual"), ("dynamic", "Dynamic")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "match_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Dynamic: screens with any of these tags.",
                        verbose_name="tags",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screen_groups",
                        to="events.event",
                    ),
                ),
                (
                    "match_rooms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="venues.room",
                        verbose_name="rooms",
                    ),
                ),
                (
                    "match_venues",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="venues.venue",
                        verbose_name="venues",
                    ),
                ),
                (
                    "match_zones",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="venues.zone",
                        verbose_name="zones",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="screen",
            name="manual_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="manual_screens",
                to="screens.screengroup",
                verbose_name="groups",
            ),
        ),
        migrations.AddConstraint(
            model_name="screengroup",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="screens_group_unique_name"
            ),
        ),
    ]
