# Generated by Django 5.2.17 on 2026-10-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screens", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="logs",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="screen",
            name="logs_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="screenshot_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="screenshot_error",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
