# Generated by Django 5.2.17 on 2026-10-10 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screens", "0002_remote_management"),
        ("venues", "0003_floor_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="facing",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="floor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="venues.floor",
            ),
        ),
    ]
