# Generated by Django 5.2.17 on 2026-10-10 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("venues", "0004_floor_georeference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvacState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("staff_alert", "Staff alert"),
                            ("attention", "Attention"),
                            ("shelter_in_place", "Shelter in place"),
                            ("evacuate", "Evacuate"),
                            ("all_clear", "All clear"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("drill", models.BooleanField(default=False)),
                ("since", models.DateTimeField(blank=True, null=True)),
                ("clear_until", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=40)),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evac_states",
                        to="events.event",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evac_states",
                        to="venues.zone",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "zone"), name="evac_state_event_zone"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("zone__isnull", True)),
                        fields=("event",),
                        name="evac_state_event",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StateChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("zone_name", models.CharField(blank=True, max_length=200)),
                ("at", models.DateTimeField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("raise", "raise"),
                            ("escalate", "escalate"),
                            ("step_down", "step down"),
                            ("replace_drill", "replace drill"),
                            ("clear", "clear"),
                            ("end", "end"),
                            ("drill_ended", "drill ended"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "from_state",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("staff_alert", "Staff alert"),
                            ("attention", "Attention"),
                            ("shelter_in_place", "Shelter in place"),
                            ("evacuate", "Evacuate"),
                            ("all_clear", "All clear"),
                        ],
                        max_length=20,
                    ),
                ),
                ("from_drill", models.BooleanField(default=False)),
                (
                    "to_state",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("staff_alert", "Staff alert"),
                            ("attention", "Attention"),
                            ("shelter_in_place", "Shelter in place"),
                            ("evacuate", "Evacuate"),
                            ("all_clear", "All clear"),
                        ],
                        max_length=20,
                    ),
                ),
                ("drill", models.BooleanField(default=False)),
                ("actor_repr", models.CharField(blank=True, max_length=200)),
                ("source", models.CharField(blank=True, max_length=40)),
                ("reason", models.CharField(blank=True, max_length=300)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evac_changes",
                        to="events.event",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="venues.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
                "indexes": [
                    models.Index(
                        fields=["event", "-at"], name="evacuation__event_i_eee290_idx"
                    )
                ],
            },
        ),
    ]
