# Generated by Django 5.2.17 on 2026-10-10 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evacuation", "0002_blocked_points"),
        ("events", "0001_initial"),
        ("venues", "0004_floor_georeference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledDrill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("at", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("staff_alert", "Staff alert"),
                            ("attention", "Attention"),
                            ("shelter_in_place", "Shelter in place"),
                            ("evacuate", "Evacuate"),
                            ("all_clear", "All clear"),
                        ],
                        default="evacuate",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("outcome", models.CharField(blank=True, max_length=300)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evac_drills",
                        to="events.event",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="venues.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["at"],
            },
        ),
        migrations.CreateModel(
            name="EvacPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.CharField(max_length=40)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "Normal"),
                            ("staff_alert", "Staff alert"),
                            ("attention", "Attention"),
                            ("shelter_in_place", "Shelter in place"),
                            ("evacuate", "Evacuate"),
                            ("all_clear", "All clear"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("execute", "Execute at once"),
                            ("arm", "Arm: the control room confirms"),
                            ("notify", "Only notify the control room"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "escalate_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evac_policies",
                        to="events.event",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="venues.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["source", "state"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "source", "state", "zone"),
                        name="evac_policy_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EvacRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("arm", "Waiting for the control room"),
                            ("second", "Waiting for a second person"),
                        ],
                        max_length=10,
                    ),
                ),
                ("source", models.CharField(max_length=40)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("staff_alert", "Staff alert"),
                            ("attention", "Attention"),
                            ("shelter_in_place", "Shelter in place"),
                            ("evacuate", "Evacuate"),
                            ("all_clear", "All clear"),
                        ],
                        max_length=20,
                    ),
                ),
                ("drill", models.BooleanField(default=False)),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("clear_zones", models.JSONField(blank=True, null=True)),
                ("requested_repr", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField()),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "escalate_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("executed", "executed at once"),
                            ("confirmed", "confirmed"),
                            ("rejected", "rejected"),
                            ("escalated", "escalated"),
                            ("expired", "expired"),
                            ("notified", "notified"),
                            ("superseded", "superseded"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("key", models.CharField(blank=True, max_length=100)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evac_requests",
                        to="events.event",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="venues.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "deadline"],
                        name="evacuation__status_b5baf9_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("key", ""), _negated=True),
                        fields=("event", "key"),
                        name="evac_request_key",
                    )
                ],
            },
        ),
    ]
