# Generated by Django 5.2.17 on 2026-10-10 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evacuation", "0004_bridges"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAlarm",
            fields=[
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="evac_alarm",
                        serialize=False,
                        to="events.event",
                    ),
                ),
                ("seq", models.PositiveBigIntegerField(default=0)),
                ("public_key", models.CharField(blank=True, max_length=100)),
                ("private_key_encrypted", models.TextField(blank=True)),
                ("previous_public_key", models.CharField(blank=True, max_length=100)),
                ("previous_valid_until", models.DateTimeField(blank=True, null=True)),
                ("key_created_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StageContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("staff_alert", "Staff alert"),
                            ("attention", "Attention"),
                            ("shelter_in_place", "Shelter in place"),
                            ("evacuate", "Evacuate"),
                            ("all_clear", "All clear"),
                        ],
                        max_length=20,
                    ),
                ),
                ("layout_id", models.UUIDField(blank=True, null=True)),
                ("texts", models.JSONField(blank=True, default=list)),
                ("rotate_seconds", models.PositiveIntegerField(default=8)),
                ("pictograms_only", models.BooleanField(default=False)),
                (
                    "sound",
                    models.CharField(
                        choices=[
                            ("siren", "Siren"),
                            ("gong", "Gong"),
                            ("alert", "Alert tone"),
                            ("none", "No sound"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("sound_every", models.PositiveIntegerField(default=30)),
                ("speech_text", models.CharField(blank=True, max_length=500)),
                ("speech_file", models.CharField(blank=True, max_length=100)),
                ("speech_status", models.CharField(blank=True, max_length=10)),
                ("speech_detail", models.CharField(blank=True, max_length=300)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evac_content",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "state"), name="evac_content_event_state"
                    )
                ],
            },
        ),
    ]
