# Generated by Django 5.2.17 on 2026-10-10 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evacuation", "0005_stage_content"),
        ("events", "0001_initial"),
        ("venues", "0004_floor_georeference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreenAck",
            fields=[
                ("screen_id", models.UUIDField(primary_key=True, serialize=False)),
                ("seq", models.PositiveBigIntegerField(default=0)),
                ("version", models.CharField(blank=True, max_length=32)),
                ("state", models.CharField(blank=True, max_length=20)),
                ("drill", models.BooleanField(default=False)),
                ("via", models.CharField(blank=True, max_length=20)),
                ("rendered_at", models.DateTimeField(blank=True, null=True)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("received_at", models.DateTimeField(auto_now=True)),
                ("fallback", models.BooleanField(default=False)),
                ("detail", models.CharField(blank=True, max_length=200)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evac_screen_acks",
                        to="events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffAck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_repr", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("on_it", "I'm on it"),
                            ("zone_clear", "Zone clear"),
                            ("need_help", "Need help"),
                        ],
                        max_length=12,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("seq", models.PositiveBigIntegerField(default=0)),
                ("drill", models.BooleanField(default=False)),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evac_staff_acks",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="venues.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="LatencySample",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("seq", models.PositiveBigIntegerField()),
                ("screen_id", models.UUIDField()),
                ("latency_ms", models.PositiveIntegerField()),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event", "-at"], name="evacuation__event_i_69bb82_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("seq", "screen_id", "event"), name="evac_latency_once"
                    )
                ],
            },
        ),
    ]
