# Generated by Django 5.2.17 on 2026-10-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evacuation", "0006_acks"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventalarm",
            name="seq_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventalarm",
            name="watchdog_seq",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="screenack",
            name="bundle_served",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="screenack",
            name="bundle_served_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenack",
            name="selftest",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="screenack",
            name="selftest_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
