# Generated by Django 5.2.17 on 2026-10-10 21:28

import apps.inventory.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("venues", "0004_floor_georeference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                (
                    "loan_hours",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Suggested due time when lending. 0: no due time.",
                        verbose_name="usual loan (hours)",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_categories",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "asset_tag",
                    models.CharField(
                        help_text="Empty: the next free number.",
                        max_length=40,
                        verbose_name="asset tag",
                    ),
                ),
                (
                    "serial",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="serial number"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("lent", "Lent"),
                            ("maintenance", "Maintenance"),
                            ("missing", "Missing"),
                            ("retired", "Retired"),
                        ],
                        default="available",
                        max_length=12,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Shelf B3",
                        max_length=120,
                        verbose_name="where exactly",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.inventory.models._photo_path,
                        verbose_name="photo",
                    ),
                ),
                ("position_x", models.FloatField(blank=True, null=True)),
                ("position_y", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="inventory.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="events.event",
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="venues.floor",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="venues.room",
                        verbose_name="kept in",
                    ),
                ),
            ],
            options={
                "ordering": ["asset_tag"],
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("borrower", models.CharField(max_length=120, verbose_name="lent to")),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        help_text="Phone, DECT or team.",
                        max_length=120,
                        verbose_name="contact",
                    ),
                ),
                ("lent_at", models.DateTimeField()),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="due back"
                    ),
                ),
                (
                    "signature",
                    models.ImageField(
                        blank=True, upload_to=apps.inventory.models._photo_path
                    ),
                ),
                (
                    "photo_out",
                    models.ImageField(
                        blank=True, upload_to=apps.inventory.models._photo_path
                    ),
                ),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ok", "OK"),
                            ("damaged", "Damaged"),
                            ("incomplete", "Incomplete"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "photo_back",
                    models.ImageField(
                        blank=True, upload_to=apps.inventory.models._photo_path
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("reminded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "borrower_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="account",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="inventory.item",
                    ),
                ),
                (
                    "lent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "returned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-lent_at"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("maintenance", "Maintenance"),
                            ("damage", "Damage"),
                            ("status", "Status"),
                        ],
                        default="note",
                        max_length=12,
                    ),
                ),
                ("text", models.TextField()),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
            },
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="inventory_category_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("event", "asset_tag"), name="inventory_item_tag"
            ),
        ),
    ]
