# Generated by Django 5.2.17 on 2026-10-09 12:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0003_layouts"),
        ("events", "0001_initial"),
        ("screens", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("ordered", "In order"),
                            ("shuffle", "Shuffled (same order on every screen)"),
                            (
                                "weighted",
                                "Weighted (items with more weight come more often)",
                            ),
                        ],
                        default="ordered",
                        max_length=10,
                        verbose_name="order",
                    ),
                ),
                (
                    "default_duration",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Used when neither the item nor the layout sets a duration.",
                        verbose_name="seconds per slide",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Plays when no schedule or override applies.",
                        verbose_name="default playlist of the event",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlists",
                        to="events.event",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Override",
            fields=[
                (
                    "all_screens",
                    models.BooleanField(default=False, verbose_name="all screens"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent (above schedules)"),
                            ("override", "Live override"),
                            (
                                "emergency",
                                "Emergency (above everything except evacuation)",
                            ),
                        ],
                        default="override",
                        max_length=10,
                        verbose_name="level",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Shown in large letters when no layout or playlist is chosen.",
                        verbose_name="message",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="starts"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Empty: until cancelled.",
                        null=True,
                        verbose_name="ends",
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="events.event",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="screens.screengroup",
                        verbose_name="screen groups",
                    ),
                ),
                (
                    "layout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="content.layout",
                        verbose_name="layout",
                    ),
                ),
                (
                    "screens",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="screens.screen",
                        verbose_name="screens",
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="playlists.playlist",
                        verbose_name="playlist",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlaylistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Empty: the layout's own duration or the playlist default.",
                        null=True,
                        verbose_name="seconds",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Weighted playlists: 3 means three times as often as 1.",
                        verbose_name="weight",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="only on screens tagged"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        help_text='e.g. screen.zone == "North" or not screen.room',
                        max_length=300,
                        verbose_name="show only if",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(blank=True, null=True, verbose_name="from"),
                ),
                (
                    "valid_until",
                    models.DateTimeField(blank=True, null=True, verbose_name="until"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_in",
                        to="playlists.playlist",
                        verbose_name="nested playlist",
                    ),
                ),
                (
                    "layout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="content.layout",
                        verbose_name="layout",
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="playlists.playlist",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "all_screens",
                    models.BooleanField(default=False, verbose_name="all screens"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="0-99. When schedules overlap, the higher number wins.",
                        verbose_name="priority",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="first day"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="last day"),
                ),
                (
                    "weekdays",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Empty: every day. 0 = Monday … 6 = Sunday.",
                        verbose_name="weekdays",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Empty: from midnight.",
                        null=True,
                        verbose_name="from",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True,
                        help_text="Empty: until midnight. Earlier than the start runs past midnight.",
                        null=True,
                        verbose_name="until",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_rules",
                        to="events.event",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="screens.screengroup",
                        verbose_name="screen groups",
                    ),
                ),
                (
                    "layout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="content.layout",
                        verbose_name="layout",
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="playlists.playlist",
                        verbose_name="playlist",
                    ),
                ),
                (
                    "screens",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="screens.screen",
                        verbose_name="screens",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="playlist",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="playlists_playlist_unique_name"
            ),
        ),
    ]
