# Generated by Django 5.2.17 on 2026-10-10 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("venues", "0004_floor_georeference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="title")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="subtitle"
                    ),
                ),
                ("abstract", models.TextField(blank=True, verbose_name="abstract")),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="language"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        help_text="e.g. talk, workshop, concert",
                        max_length=60,
                        verbose_name="type",
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, max_length=500, verbose_name="link"),
                ),
                (
                    "starts_at",
                    models.DateTimeField(db_index=True, verbose_name="starts"),
                ),
                ("ends_at", models.DateTimeField(verbose_name="ends")),
                ("planned_start", models.DateTimeField(blank=True, null=True)),
                ("planned_end", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=10,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Shown with the session, e.g. “Moved to Hall B” or “Starts 15 min late”.",
                        max_length=200,
                        verbose_name="note on screens",
                    ),
                ),
                ("public", models.BooleanField(default=True, verbose_name="public")),
                ("source", models.CharField(blank=True, max_length=80)),
                (
                    "external_id",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("overrides", models.JSONField(blank=True, default=list)),
                ("missing_upstream", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at", "stage__order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SessionChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("delay", "Delayed"),
                            ("earlier", "Earlier"),
                            ("cancel", "Cancelled"),
                            ("room", "Room changed"),
                            ("time", "New time"),
                            ("restore", "Back to plan"),
                            ("new", "Added"),
                        ],
                        max_length=10,
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_changes",
                        to="events.event",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="schedule.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("bio", models.TextField(blank=True, verbose_name="biography")),
                ("source", models.CharField(blank=True, max_length=80)),
                ("external_id", models.CharField(blank=True, max_length=200)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakers",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="session",
            name="speakers",
            field=models.ManyToManyField(
                blank=True,
                related_name="sessions",
                to="schedule.speaker",
                verbose_name="speakers",
            ),
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("order", models.IntegerField(default=0, verbose_name="order")),
                ("source", models.CharField(blank=True, max_length=80)),
                ("external_id", models.CharField(blank=True, max_length=200)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="events.event",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="venues.room",
                        verbose_name="venue room",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="session",
            name="planned_stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="schedule.stage",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="schedule.stage",
                verbose_name="room / stage",
            ),
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "colour",
                    models.CharField(
                        default="#64748b", max_length=7, verbose_name="colour"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="session",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="schedule.track",
                verbose_name="track",
            ),
        ),
        migrations.AddConstraint(
            model_name="stage",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="schedule_stage_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="track",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="schedule_track_name"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["event", "starts_at"], name="schedule_se_event_i_66ad69_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("event", "source", "external_id"),
                name="schedule_session_source",
            ),
        ),
    ]
