# Generated by Django 5.2.17 on 2026-10-10 21:33

import apps.helpdesk.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("venues", "0004_floor_georeference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.CharField(max_length=200, verbose_name="question")),
                ("answer", models.TextField(verbose_name="answer")),
                (
                    "topic",
                    models.CharField(
                        blank=True,
                        help_text="Groups the questions.",
                        max_length=60,
                        verbose_name="topic",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "public",
                    models.BooleanField(
                        default=True, verbose_name="on the public help page"
                    ),
                ),
                (
                    "on_screens",
                    models.BooleanField(default=False, verbose_name="on screens"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faq_entries",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["topic", "order", "question"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(max_length=12)),
                ("subject", models.CharField(max_length=160, verbose_name="subject")),
                ("body", models.TextField(verbose_name="message")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("question", "Question"),
                            ("problem", "Problem"),
                            ("accessibility", "Accessibility"),
                            ("feedback", "Feedback"),
                            ("other", "Other"),
                        ],
                        default="question",
                        max_length=14,
                        verbose_name="about",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=120, verbose_name="name"),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        help_text="Phone or e-mail if you want an answer.",
                        max_length=200,
                        verbose_name="contact",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("open", "In progress"),
                            ("waiting", "Waiting"),
                            ("done", "Done"),
                        ],
                        default="new",
                        max_length=8,
                    ),
                ),
                ("source", models.CharField(default="staff", max_length=10)),
                (
                    "token",
                    models.CharField(
                        default=apps.helpdesk.models._token,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned to",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "public",
                    models.BooleanField(
                        default=False,
                        help_text="A reply the requester sees on the status page.",
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="helpdesk.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["at"],
            },
        ),
        migrations.CreateModel(
            name="LostFound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("lost", "Lost"), ("found", "Found")], max_length=5
                    ),
                ),
                ("reference", models.CharField(max_length=12)),
                (
                    "what",
                    models.CharField(
                        help_text="e.g. Black backpack",
                        max_length=120,
                        verbose_name="what",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bag", "Bag or backpack"),
                            ("clothing", "Clothing"),
                            ("electronics", "Phone or electronics"),
                            ("keys", "Keys"),
                            ("wallet", "Wallet, cards or documents"),
                            ("jewellery", "Jewellery or watch"),
                            ("glasses", "Glasses"),
                            ("bottle", "Bottle or cup"),
                            ("toy", "Toy"),
                            ("other", "Something else"),
                        ],
                        default="other",
                        max_length=12,
                        verbose_name="category",
                    ),
                ),
                (
                    "colour",
                    models.CharField(blank=True, max_length=40, verbose_name="colour"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brand, contents, marks. Not shown on the public page.",
                        verbose_name="details",
                    ),
                ),
                (
                    "where",
                    models.CharField(blank=True, max_length=120, verbose_name="where"),
                ),
                (
                    "when",
                    models.DateTimeField(blank=True, null=True, verbose_name="when"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.helpdesk.models._photo_path,
                        verbose_name="photo",
                    ),
                ),
                (
                    "storage",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Helpdesk box 3",
                        max_length=120,
                        verbose_name="kept at",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=120, verbose_name="name"),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        help_text="Phone or e-mail, only for the helpdesk.",
                        max_length=200,
                        verbose_name="contact",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("matched", "Matched"),
                            ("returned", "Returned"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "handed_to",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="handed to"
                    ),
                ),
                ("handed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "public",
                    models.BooleanField(
                        default=True,
                        help_text="Found items: what, category, colour and day on the public page.",
                        verbose_name="list publicly",
                    ),
                ),
                ("source", models.CharField(default="staff", max_length=10)),
                (
                    "token",
                    models.CharField(
                        default=apps.helpdesk.models._token,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lost_found",
                        to="events.event",
                    ),
                ),
                (
                    "handed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="helpdesk.lostfound",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="venues.room",
                        verbose_name="room",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "reference"), name="helpdesk_lf_reference"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("event", "reference"), name="helpdesk_ticket_reference"
            ),
        ),
    ]
