# Generated by Django 5.2.17 on 2026-10-10 20:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("screens", "0003_screen_map_place"),
        ("venues", "0004_floor_georeference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="People allowed at once. 0: count only, no rule.",
                        verbose_name="capacity",
                    ),
                ),
                (
                    "busy_percent",
                    models.PositiveSmallIntegerField(
                        default=80, verbose_name="busy from (%)"
                    ),
                ),
                (
                    "full_percent",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="full from (%)"
                    ),
                ),
                (
                    "release_percent",
                    models.PositiveSmallIntegerField(
                        default=90,
                        help_text="“Full” ends only when the count falls below this, so the sign does not flicker at the limit.",
                        verbose_name="open again below (%)",
                    ),
                ),
                (
                    "show_on_screens",
                    models.BooleanField(
                        default=True, verbose_name="show “full” on screens"
                    ),
                ),
                (
                    "full_text",
                    models.CharField(
                        blank=True,
                        help_text="Empty: “{name} is full” and the alternative.",
                        max_length=200,
                        verbose_name="text when full",
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        blank=True, default=list, verbose_name="also alert channels"
                    ),
                ),
                (
                    "sensor_key",
                    models.SlugField(
                        blank=True,
                        help_text="For sensors over MQTT: <prefix>/crowd/<event>/<sensor key>.",
                        max_length=60,
                        verbose_name="sensor key",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="order")),
                ("value", models.IntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("busy", "Busy"),
                            ("full", "Full"),
                        ],
                        default="normal",
                        max_length=6,
                    ),
                ),
                ("state_since", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "alternative",
                    models.ForeignKey(
                        blank=True,
                        help_text="Suggested on the screens while it has space.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crowd.area",
                        verbose_name="send people to",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crowd_areas",
                        to="events.event",
                    ),
                ),
                (
                    "notify_roles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Their members get an alert when it is full and when it opens again.",
                        related_name="+",
                        to="events.role",
                        verbose_name="alert roles",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Screens in this room show “full”.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="venues.room",
                        verbose_name="room",
                    ),
                ),
                (
                    "screen_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="e.g. the foyer screens that send people to the hall.",
                        related_name="+",
                        to="screens.screengroup",
                        verbose_name="also on screen groups",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        help_text="Or a whole zone (screens in the zone).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="venues.zone",
                        verbose_name="zone",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CountEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("at", models.DateTimeField(db_index=True)),
                ("delta", models.IntegerField()),
                ("value_after", models.IntegerField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("clicker", "Door counter"),
                            ("sensor", "Sensor"),
                            ("mqtt", "Sensor (MQTT)"),
                            ("api", "API"),
                            ("scanner", "Ticket scanner"),
                            ("correction", "Correction"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        blank=True, help_text="door or device label", max_length=80
                    ),
                ),
                ("client_id", models.CharField(blank=True, max_length=64)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counts",
                        to="crowd.area",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("minute", models.DateTimeField()),
                ("value", models.IntegerField()),
                ("peak", models.IntegerField()),
                ("low", models.IntegerField()),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="crowd.area",
                    ),
                ),
            ],
            options={
                "ordering": ["minute"],
            },
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="crowd_area_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sensor_key", ""), _negated=True),
                fields=("event", "sensor_key"),
                name="crowd_area_sensor_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="countevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_id", ""), _negated=True),
                fields=("area", "client_id"),
                name="crowd_count_client_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="sample",
            constraint=models.UniqueConstraint(
                fields=("area", "minute"), name="crowd_sample_minute"
            ),
        ),
    ]
