# Generated by Django 5.2.17 on 2026-10-09 23:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SigningKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("private_key_encrypted", models.TextField()),
                ("public_key", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PackImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("url", "URL"),
                            ("gallery", "Gallery"),
                        ],
                        max_length=8,
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=1000)),
                ("gallery_key", models.CharField(blank=True, max_length=64)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("size", models.PositiveBigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("fetching", "Downloading"),
                            ("ready", "Ready to import"),
                            ("failed", "Failed"),
                            ("imported", "Imported"),
                        ],
                        default="fetching",
                        max_length=8,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("contents", models.JSONField(blank=True, default=dict)),
                (
                    "trust",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("builtin", "Built in"),
                            ("trusted", "Signed by a trusted key"),
                            ("untrusted", "Signed by an unknown key"),
                            ("unsigned", "Not signed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("signer", models.CharField(blank=True, max_length=200)),
                ("public_key", models.CharField(blank=True, max_length=64)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_imports",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrustedKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("public_key", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
