# Generated by Django 5.2.17 on 2026-10-10 23:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0003_layouts"),
        ("events", "0001_initial"),
        ("venues", "0004_floor_georeference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Main entrance, Backstage, Crew area",
                        max_length=80,
                        verbose_name="name",
                    ),
                ),
                (
                    "open_to_all",
                    models.BooleanField(
                        default=False,
                        help_text="Off: only the ticket types that grant this zone.",
                        verbose_name="every valid ticket",
                    ),
                ),
                (
                    "checkin",
                    models.BooleanField(
                        default=False,
                        help_text="The first scan into this zone checks the attendee in (the entrance).",
                        verbose_name="checks in",
                    ),
                ),
                (
                    "reentry",
                    models.BooleanField(
                        default=True,
                        help_text="Off: a ticket that is already inside is refused.",
                        verbose_name="re-entry allowed",
                    ),
                ),
                (
                    "area_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Scans in and out count people in this occupancy area.",
                        null=True,
                        verbose_name="occupancy area",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_zones",
                        to="events.event",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="venues.room",
                        verbose_name="room",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Attendee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="organisation"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Empty: a new random code.",
                        max_length=128,
                        verbose_name="ticket code",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("cancelled", "Cancelled"),
                            ("blocked", "Blocked"),
                        ],
                        default="valid",
                        max_length=10,
                    ),
                ),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("badge_printed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("source", models.CharField(blank=True, max_length=60)),
                ("external_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Presence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inside", models.BooleanField(default=False)),
                ("since", models.DateTimeField()),
                (
                    "attendee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presence",
                        to="access.attendee",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presence",
                        to="access.accesszone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code_hint",
                    models.CharField(
                        blank=True,
                        help_text="The last characters of an unknown code.",
                        max_length=8,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "In"), ("out", "Out")],
                        default="in",
                        max_length=3,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("denied", "Not allowed"),
                            ("duplicate", "Already inside"),
                            ("invalid", "Cancelled or blocked"),
                            ("unknown", "Unknown ticket"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        help_text="When it was scanned (the device's time for offline scans)."
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("offline", models.BooleanField(default=False)),
                ("device", models.CharField(blank=True, max_length=80)),
                ("client_id", models.CharField(blank=True, max_length=64)),
                ("source", models.CharField(blank=True, max_length=60)),
                (
                    "attendee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scans",
                        to="access.attendee",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="access.accesszone",
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Day ticket, Crew, Artist",
                        max_length=80,
                        verbose_name="name",
                    ),
                ),
                (
                    "colour",
                    models.CharField(
                        default="#2563eb",
                        help_text="Wristband or badge colour.",
                        max_length=7,
                        verbose_name="colour",
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=60)),
                ("external_id", models.CharField(blank=True, max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "badge_layout",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty: the built-in badge.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="content.layout",
                        verbose_name="badge layout",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_types",
                        to="events.event",
                    ),
                ),
                (
                    "zones",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ticket_types",
                        to="access.accesszone",
                        verbose_name="grants zones",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="attendee",
            name="ticket_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendees",
                to="access.tickettype",
                verbose_name="ticket type",
            ),
        ),
        migrations.AddConstraint(
            model_name="accesszone",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="access_zone_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="presence",
            constraint=models.UniqueConstraint(
                fields=("attendee", "zone"), name="access_presence"
            ),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(
                fields=["zone", "-at"], name="access_scan_zone_id_ce3d57_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="scan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_id", ""), _negated=True),
                fields=("event", "client_id"),
                name="access_scan_client_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendee",
            constraint=models.UniqueConstraint(
                fields=("event", "code"), name="access_attendee_code"
            ),
        ),
    ]
