# Generated by Django 5.2.17 on 2026-10-10 07:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("waypoint", "Waypoint"),
                            ("door", "Door"),
                            ("stairs", "Stairs"),
                            ("lift", "Lift"),
                            ("exit", "Exit"),
                            ("assembly", "Assembly point"),
                        ],
                        default="waypoint",
                        max_length=10,
                        verbose_name="kind",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "x",
                    models.FloatField(
                        default=0,
                        help_text="Metres from the left edge of the floor plan.",
                        verbose_name="x (m)",
                    ),
                ),
                (
                    "y",
                    models.FloatField(
                        default=0,
                        help_text="Metres from the top edge of the floor plan.",
                        verbose_name="y (m)",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Exits: people per minute; assembly points: people. Informational for now.",
                        null=True,
                        verbose_name="capacity",
                    ),
                ),
                (
                    "step_free",
                    models.BooleanField(
                        default=True,
                        help_text="Usable with a wheelchair (stairs usually are not).",
                        verbose_name="step-free",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=300, verbose_name="note"),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty: outdoors at ground level.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="points",
                        to="venues.floor",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="points",
                        to="venues.room",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="venues.venue",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="points",
                        to="venues.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "name"],
            },
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "one_way",
                    models.BooleanField(
                        default=False,
                        help_text="Only from the first to the second point (e.g. an exit-only door).",
                        verbose_name="one way",
                    ),
                ),
                (
                    "length_m",
                    models.FloatField(
                        blank=True,
                        help_text="Empty: the straight distance (plus 5 m per floor).",
                        null=True,
                        verbose_name="length (m)",
                    ),
                ),
                (
                    "step_free",
                    models.BooleanField(default=True, verbose_name="step-free"),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges",
                        to="venues.venue",
                    ),
                ),
                (
                    "a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges_out",
                        to="venues.point",
                        verbose_name="from",
                    ),
                ),
                (
                    "b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges_in",
                        to="venues.point",
                        verbose_name="to",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="point",
            index=models.Index(
                fields=["venue", "kind"], name="venues_poin_venue_i_1cfd1f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="edge",
            constraint=models.UniqueConstraint(
                fields=("a", "b"), name="venues_edge_unique_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="edge",
            constraint=models.CheckConstraint(
                condition=models.Q(("a", models.F("b")), _negated=True),
                name="venues_edge_not_loop",
            ),
        ),
    ]
