# Generated by Django 5.2.17 on 2026-10-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0002_route_graph"),
    ]

    operations = [
        migrations.AddField(
            model_name="floor",
            name="metres_per_px",
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name="floor",
            name="plan_file",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="floor",
            name="plan_height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="floor",
            name="plan_scaled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="floor",
            name="plan_width",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="zone",
            name="areas",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
