# Generated by Django 5.2.17 on 2026-10-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0003_floor_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="floor",
            name="geo_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="floor",
            name="geo_lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="floor",
            name="geo_rotation",
            field=models.FloatField(default=0),
        ),
    ]
